import mongoose, {model, Schema} from 'mongoose'

const restaurantSchema = new Schema({
    ownerId:{
        type:Schema.Types.ObjectId,
        required:true,
        ref:"User"
    },
    name:{
        type:String,
        lowercase:true,
        unique:true,
        required:true
    },
    address:{
        type:String,
        lowercase:true,
        unique:true,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true,
        lowercase:true,
        trim:true
    },
    contact:{
        type:String,
        unique:true,
        required:true
    },
    rating:{
        type:Number
    },
    cusines:[
        {
            category: {
                type:String,
                lowercase:true,
            },
            food:[
                {
                    name:String,
                    price:Number,
                    description:String,
                    images:[
                        {
                          type:String  
                        }
                    ]
                }
            ]
        }
    ],
    coverImage:{
        type:String
    },
    reviews:[
        {
            userId:{
                type:Schema.Types.ObjectId,
                ref:"User"
            },
            rating:{
                type:Number,
                min:1,
                max:5
            },
            message:{
                type:String,
                trim:true
            },
            username:{
                type:String
            }
        }
    ],
    restaurantStatus:{
        type:Boolean,
        default:true
    }
},{
    timestamps:true
})

export default mongoose.model("Restaurant",restaurantSchema)